version: '3.8'
services:
  app:
    build:
      context: .
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./:/usr/src/app/
    ports:
      - '3000:3000'
    command: sh -c "npm run dev"
