version: '3.8'
services:
  app:
    build:
      context: .
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./:/usr/src/app/
      - node-modules-volume:/usr/src/app/node_modules
    ports:
      - '3000:3000'
volumes:
  node-modules-volume:
